### ISSUE TITLE
Program Settings To-Do List (For Roles)

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mPATH#4138]
**Program Settings Projects and Contracts (Roles work)**
- [ ] Ability to save multiple users at a time
- [ ] Actions column to edit users/roles
- [ ] (maybe change embedded roles table to modal)

**Program Settings Roles**
- [ ] Ability to add users to program admin roles
- [ ] Ability to edit privileges

**Program Settings Users**
